# This is a basic workflow to help you get started with Actions

name: Approver Workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      issues: write
    environment:
      name: prod
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{secrets.GITHUB_TOKEN}}
          approvers: hasan-saghir
          minimum-approvals: 1
          issue-title: "Prod Deployment Docs Check"
          issue-body: "Make sure Security Review, Change Request (CR) & Testing Report have been created and updated in Confluence. You may also add this on the Issue. comment `done` and closed the issue"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'done'
          additional-denied-words: ''
      
      - name: Deploying
        run: echo Deploying to Prod
